#pragma once

#include "rclcpp/rclcpp.hpp"

// auto-generated by generate_parameter_library
#include "{{cookiecutter.package_name}}_parameters.hpp"

#include "{{cookiecutter.package_name}}/visibility_control.h"

namespace {{cookiecutter.package_name}}
{

class {{cookiecutter.__class_name}} : public rclcpp::Node
{
public:
  {{cookiecutter.__class_name}}(const rclcpp::NodeOptions& options);
};

}  // namespace {{cookiecutter.package_name}}
